### ISSUE TITLE
Печать тегов с новой строки

### ISSUE THREAD

**Issue by jenokizm** [utlime/php-social-meta-tags#2]
![image](https://user-images.githubusercontent.com/11296510/35775523-01dc5e26-099b-11e8-9692-d9076ec2e664.png)

Сейчас у вас теги выводятся подряд, было бы хорошими тоном каждый с новой строки.
Вероятно 
`$build .= $this->meta->current()->asXML();`
заменить на 
`$build .= $this->meta->current()->asXML().PHP_EOL;`

**Comment by utlime** [comment]
Привет @jenokizm, спасибо за предложение.
Но данная возможность относится к форматированию, а не к генерации.

Если вы хотите получить красивый вывод вы можете посмотреть вывод в браузере.
