### ISSUE TITLE
Выводит кракозябы если значения параметров на русском

### ISSUE THREAD

**Issue by jenokizm** [utlime/php-social-meta-tags#3]
пример:
```
$meta = $builder
    ->add('title', 'русский')
    ->add('description', 'english')
    ->build();
```
результат на скрине:
![image](https://user-images.githubusercontent.com/11296510/35775624-7db8831a-099d-11e8-9cf6-7b350b8d573c.png)
даже декодер лебедева не понимает формат https://www.artlebedev.ru/decoder/

**Comment by utlime** [comment]
Здравствуйте @jenokizm,
я проверял работу этого пакета для работы с кирилицой. Возможно вы не настроили кодировку в php.
Попробуйте привести ваш текст к utf-8

**Comment by jenokizm** [comment]
Привет, у меня utf-8 везде. Значит не мешало бы еще раз проверить.

**Comment by jenokizm** [comment]
Я понял это же html entities. Не все приложения og ее понимают и корректно отображают. Временное решение `return html_entity_decode($build);`
