### ISSUE TITLE
Needs set() and unset()

### ISSUE THREAD

**Issue by jerry1970** [utlime/php-social-meta-tags#4]
Because the class does not feature a set() or unset(), only add(), I had to write a mapper that keeps tags that should exist only once, like title, description, and keywords.

The controller sets a default title, then a method could set a different title, which should overwrite the first title. With just add() I would get multiple <title> tags.

**Comment by utlime** [comment]
Hi @jerry1970,
i added UniqueValueDecorator in last release, could you please check it 
https://github.com/utlime/php-seo-meta-tags/releases/tag/1.1.0

I think it should be help you
