### ISSUE TITLE
Need a reference to builder

### ISSUE THREAD

**Issue by jerry1970** [utlime/php-social-meta-tags#5]
To add the `fb:app_id` tag, I would have to extend the CommonBuilder. What about making a reference to the builders so I can use `addRule()`?

**Comment by utlime** [comment]
Hi @jerry1970 ,
You need to create you own builder, e.g. FacebookBuilder which will extend BuilderInterface.
Or you can extend AbstractBuilder and use AbstractBuilder::addRule, to process fb:app_id

Then you just need to add it to chain of builders
